Soluciono sintaxis del pipeline de CI

diff --git a/.github/workflows/poi-ci.yml b/.github/workflows/poi-ci.yml
--- a/.github/workflows/poi-ci.yml
+++ b/.github/workflows/poi-ci.yml
@@ -14,33 +14,33 @@ jobs:
       #GH Action para descargar el repo al agente.
       - uses: actions/checkout@v2
 
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v1
-      with:
-        dotnet-version: 2.1.x
-        
-    - name: restore
-      run: dotnet restore apis/poi/poi.sln     
-      
-    - name: build 
-      run: dotnet build --no-restore apis/poi/poi.sln   
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v1
+        with:
+          dotnet-version: 2.1.x
 
-    - name: Test
-      run: dotnet test --no-build --verbosity normal -r testresults --logger "trx" apis/poi/poi.sln
-      
-    - name: API POI Tests Report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()  # run this step even if previous step failed
-      with:
-        name: API POI Tests       # Name of the check run which will be created
-        path: apis/poi/tests/UnitTests/testresults/*.trx,apis/poi/tests/IntegrationTests/testresults/*.trx   #Path to test results
-        reporter: dotnet-trx      #Reporter
+      - name: restore
+        run: dotnet restore apis/poi/poi.sln
 
-#Opens An Issue Only When CI Fails   
-    - uses: actions/github-script@0.9.0
-      if: failure()
-      with:
-        github-token: ${{secrets.GITHUB_TOKEN}}
-        script: |
-          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
-          github.issues.create
+      - name: build
+        run: dotnet build --no-restore apis/poi/poi.sln
+
+      - name: Test
+        run: dotnet test --no-build --verbosity normal -r testresults --logger "trx" apis/poi/poi.sln
+
+      - name: API POI Tests Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: API POI Tests # Name of the check run which will be created
+          path: apis/poi/tests/UnitTests/testresults/*.trx,apis/poi/tests/IntegrationTests/testresults/*.trx #Path to test results
+          reporter: dotnet-trx #Reporter
+
+      #Opens An Issue Only When CI Fails
+      - uses: actions/github-script@0.9.0
+        if: failure()
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
+            github.issues.create
